# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: /home/agent/ci-agent:php
    docker:
      - image: docksal/ci-agent
    steps:
      - run:
          name: Configure agent environment
          command: echo 'source build-env' >> $BASH_ENV
      - checkout
      - run:
          name: Build sandbox
          command: |
		    build-init
			build-exex "fin init"

  deploy:
    docker:
      - image: docksal/ci-agent:php
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Testing 1 2 3"

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only:
                - master
