version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  vulnachecka: whitesource/vulnerability-checker@19.5.5

jobs:
  build:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - sonarcloud/scan

  deploy:
    docker:
      - image: docksal/ssh-agent
    steps:
      - add_ssh_keys
      - run:
          name: Add the keys to the known hosts
          command: |
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Get the latest code 
          command: |
            ssh -v $SSH_USER@$SSH_HOST "cd boilerplate-drupal8 && git pull"
      - run:
          name: Clear cache and show the status
          command: |
            ssh -v $SSH_USER@$SSH_HOST "cd boilerplate-drupal8 && fin drush cr && fin status"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - deploy:
          requires:
          - build
          #filters:
          #  branches:
          #    only:
          #      - master
     # - vulnachecka/scan:
     #     requires:
     #     - build
