# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: /home/agent/build
    docker:
      - image: docksal/ci-agent:php
    steps:
      - run:
          name: Configure agent environment
          command: echo 'source build-env' >> $BASH_ENV
      - run:
          name: Configure agent to local host
          command: fin drush status
      - checkout
      - run:
          name: Build sandbox
          command: sandbox-init

  deploy:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Testing 1 2 3"

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only:
                - master
