# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Testing 1 2 3"

  deploy:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Testing 1 2 3"

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
          - build
          filters:
            branches:
              only:
                - master
