version: 2.1

jobs:
  build:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - sonarcloud/scan

  deploy:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - vulnachecka/scan
      - run:
          name: "Testing"
          command: echo "Testing 1 2 3"

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
orbs:
  vulnachecka: whitesource/vulnerability-checker@19.5.5

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - deploy:
          requires:
          - build
          filters:
            branches:
              only:
                - master