version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  vulnachecka: whitesource/vulnerability-checker@19.5.5

jobs:
  build:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - sonarcloud/scan

  deploy:
    docker:
      - image: docksal/cli
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
             ssh $SSH_USER@$SSH_HOST
             echo "Hello from the server!"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - deploy:
          #requires:
          #- build
          #filters:
          #  branches:
          #    only:
          #      - master
     # - vulnachecka/scan:
     #     requires:
     #     - build
